###
GET http://localhost:8000/getchats/23

###

POST http://localhost:8000/inviteFriend/
Content-Type: application/json

{
    "user1": "1",
    "user2": "6",
    "type": "friend",
    "status": "pending"
}


###
GET http://localhost:8000/getMessages/3

###

GET http://localhost:8000/getNotifications/1

###

POST http://localhost:8000/acceptFriend
Content-Type: application/json

{
    "user1": "1",
    "user2": "3",
    "type": "friend"
}
###
POST http://localhost:8000/declineFriend/1/3

###
POST http://localhost:8000/blockFriend/1/3

###
POST http://localhost:8000/deblockFriend/1/3
