# Generated by Django 4.2.16 on 2024-12-29 22:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='two_factor_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Display name must be at least 5 characters long', regex='^.{5,}$')]),
        ),
    ]
