# Generated by Django 4.2.16 on 2024-11-23 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitations',
            fields=[
                ('friendship_id', models.AutoField(primary_key=True, serialize=False)),
                ('user1', models.IntegerField()),
                ('user2', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('blocked', 'Blocked')], default='pending', max_length=8)),
                ('type', models.CharField(choices=[('game', 'Game'), ('friend', 'Friend')], max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.IntegerField()),
                ('msg', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chat_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.invitations')),
            ],
        ),
        migrations.AddConstraint(
            model_name='invitations',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='unique_user_pair'),
        ),
    ]
