# Generated by Django 4.2.16 on 2024-11-17 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chats',
            fields=[
                ('chatId', models.AutoField(primary_key=True, serialize=False)),
                ('user1_ID', models.IntegerField()),
                ('user2_ID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderId', models.IntegerField()),
                ('msg', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('chatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.chats')),
            ],
        ),
        migrations.DeleteModel(
            name='msg',
        ),
    ]
